//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasMedicasApi.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialMedico
    {
        public int HistorialId { get; set; }
        public int PacienteId { get; set; }
        public int CitaId { get; set; }
        public int MedicoId { get; set; }
        public Nullable<int> NotaId { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual NotasConsulta NotasConsulta { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
