//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasMedicasApi.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Personal = new HashSet<Personal>();
        }
    
        public int UsuarioId { get; set; }
        public string Usuario { get; set; }
        public string Folio { get; set; }
        public string Contraseña { get; set; }
        public int RolId { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> PersonalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
