//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasMedicasApi.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int UsuarioId { get; set; }
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int RolId { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> PersonalId { get; set; }
        public string Correo { get; set; }
        public string RutaImagen { get; set; }
    }
}
